import BlandJensenFormal.BlandJensenMI.Main

/-!
Release gate for the public Bland--Jensen declarations.

This file deliberately uses `#print axioms`: source-text scans alone cannot
detect axioms introduced by dependencies or generated proof mechanisms.
-/

#check BlandJensenFormal.BlandJensenMI.signedWeaklyOrientable_iff_weaklyOrientable
#check BlandJensenFormal.BlandJensenMI.MI_isWeakOrientabilityExcludedMinor
#check BlandJensenFormal.BlandJensenMI.all_MI_are_weakOrientabilityExcludedMinors
#check BlandJensenFormal.BlandJensenMI.infinite_pairwise_nonisomorphic_excluded_minor_family
#check BlandJensenFormal.BlandJensenMI.bland_jensen_no_finite_excluded_minor_cover
#check BlandJensenFormal.BlandJensenMI.bland_jensen_no_finite_weakOrientability_forbiddenMinorCharacterization
#check BlandJensenFormal.BlandJensenMI.bland_jensen_no_finite_signedWeakOrientability_forbiddenMinorCharacterization

#print axioms BlandJensenFormal.BlandJensenMI.signedWeaklyOrientable_iff_weaklyOrientable
#print axioms BlandJensenFormal.BlandJensenMI.MI_isWeakOrientabilityExcludedMinor
#print axioms BlandJensenFormal.BlandJensenMI.all_MI_are_weakOrientabilityExcludedMinors
#print axioms BlandJensenFormal.BlandJensenMI.infinite_pairwise_nonisomorphic_excluded_minor_family
#print axioms BlandJensenFormal.BlandJensenMI.bland_jensen_no_finite_excluded_minor_cover
#print axioms BlandJensenFormal.BlandJensenMI.bland_jensen_no_finite_weakOrientability_forbiddenMinorCharacterization
#print axioms BlandJensenFormal.BlandJensenMI.bland_jensen_no_finite_signedWeakOrientability_forbiddenMinorCharacterization
